// <auto-generated />
using System;

using BackupMachine.Infrastructure.Persistence;
using BackupMachine.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackupMachine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BackupMachineContext))]
    [Migration("20220405061709_Backups")]
    partial class Backups
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("BackupMachine.PoC.Domain.Entities.Backup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Backups", (string)null);
                });

            modelBuilder.Entity("BackupMachine.PoC.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jobs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e005279a-2b23-4a3c-b798-27cb443daf9e"),
                            Destination = "C:\\Temp\\Backups\\SmallSource",
                            Name = "Test",
                            Source = "C:\\Temp\\Sources\\SmallSource"
                        });
                });

            modelBuilder.Entity("BackupMachine.PoC.Domain.Entities.Backup", b =>
                {
                    b.HasOne("BackupMachine.PoC.Domain.Entities.Job", "Job")
                        .WithMany("Backups")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("BackupMachine.PoC.Domain.Entities.Job", b =>
                {
                    b.Navigation("Backups");
                });
#pragma warning restore 612, 618
        }
    }
}
